packages:
  - "programs/*"
  - "ts-sdk/*"
  - "rust-sdk/*"
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@crypticdot/fusionamm-core"
  - "@crypticdot/fusionamm-client"
  - "@crypticdot/fusionamm-sdk"
  - "@crypticdot/jupiter-solana-client"