pub const HUNDRED_PERCENT: u32 = 1000000;
pub const LEVERAGE_ONE: u32 = HUNDRED_PERCENT; // 1.0x

pub const LIQUIDITY_PROVIDER_ORCA: u8 = 0;
pub const LIQUIDITY_PROVIDER_RAYDIUM: u8 = 1;

pub const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_A: u32 = 1;
pub const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_B: u32 = 1 << 1;
pub const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_A: u32 = 1 << 2;
pub const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_B: u32 = 1 << 3;
pub const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD: u32 = 1 << 4;
pub const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD_WITH_LEVERAGE: u32 = 1 << 5;
pub const TUNA_POSITION_FLAGS_MASK: u32 = (1 << 6) - 1;

pub const NO_STOP_LOSS: i32 = -2147483648;
pub const NO_TAKE_PROFIT: i32 = 2147483647;

pub const WP_NFT_UPDATE_AUTH: &str = "3axbTs2z5GBy6usVbNVoqEgZMng3vZvMnAoX29BFfwhr";
