import { address } from "@solana/kit";

export const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_A = 1;
export const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_B = 1 << 1;
export const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_A = 1 << 2;
export const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_B = 1 << 3;
export const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD = 1 << 4;
export const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD_WITH_LEVERAGE = 1 << 5;

export const NO_STOP_LOSS = -2147483648;
export const NO_TAKE_PROFIT = 2147483647;

export const WP_NFT_UPDATE_AUTH = address("3axbTs2z5GBy6usVbNVoqEgZMng3vZvMnAoX29BFfwhr");
