import { address } from "@solana/kit";

export const DEFAULT_ADDRESS = address("11111111111111111111111111111111");

export const HUNDRED_PERCENT = 1000000;
export const LEVERAGE_ONE = HUNDRED_PERCENT; // 1.0x

export const MAX_LEVERAGE = 11 * LEVERAGE_ONE;
export const MAX_PROTOCOL_FEE = HUNDRED_PERCENT / 100;
export const MAX_LIQUIDATION_FEE = HUNDRED_PERCENT / 5;
export const MAX_LIMIT_ORDER_EXECUTION_FEE = HUNDRED_PERCENT / 100;
export const DEFAULT_MAX_SWAP_SLIPPAGE = HUNDRED_PERCENT / 50;
export const MAX_LIQUIDATION_THRESHOLD = (HUNDRED_PERCENT * 95) / 100;

export const NO_STOP_LOSS = -2147483648;
export const NO_TAKE_PROFIT = 2147483647;

export const COMPUTED_AMOUNT = 18446744073709551615n;

export const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_A = 1;
export const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_B = 1 << 1;
export const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_A = 1 << 2;
export const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_B = 1 << 3;
export const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD = 1 << 4;
export const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD_WITH_LEVERAGE = 1 << 5;
export const TUNA_POSITION_FLAGS_ALLOW_REBALANCING = 1 << 6;

export const WP_NFT_UPDATE_AUTH = address("3axbTs2z5GBy6usVbNVoqEgZMng3vZvMnAoX29BFfwhr");
