pub const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_A: u32 = 1;
pub const TUNA_POSITION_FLAGS_STOP_LOSS_SWAP_TO_TOKEN_B: u32 = 1 << 1;
pub const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_A: u32 = 1 << 2;
pub const TUNA_POSITION_FLAGS_TAKE_PROFIT_SWAP_TO_TOKEN_B: u32 = 1 << 3;
pub const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD: u32 = 1 << 4;
pub const TUNA_POSITION_FLAGS_AUTO_COMPOUND_YIELD_WITH_LEVERAGE: u32 = 1 << 5;
pub const TUNA_POSITION_FLAGS_MASK: u32 = (1 << 6) - 1;